---
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: node-shell
spec:
  version: {{ .TagName }}
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/Moon1706/node-shell/releases/download/{{ .TagName }}/node-shell_linux_amd64.tar.gz" .TagName }}
      files:
        - from: "./node-shell"
          to: "."
        - from: LICENSE
          to: "."
      bin: "node-shell"
  shortDescription: A new plugin
  homepage: https://github.com/Moon1706/node-shell
  caveats: |
    Usage:
      $ kubectl node-shell --debug-image=<debug-image> --nodename=<node-to-run-on>

    For additional options:
      $ kubectl node-shell --help
      or https://github.com/Tinkoff/node-shell/blob/main/README.md

  description: |
    Kubectl plugin to run on a specific node with host filesystem mounted and escalated privileges
