---
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: node-shell
spec:
  version: "v0.0.1"
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/Moon1706/node-shell/releases/download/v0.0.1/node-shell_linux_amd64.tar.gz
      sha256: "7094515f52ce62e88055728a5053c457f510d5fe145ad6901af9ba278a6978f5"
      files:
        - from: "./node-shell"
          to: "."
        - from: LICENSE
          to: "."
      bin: "node-shell"
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/Moon1706/node-shell/releases/download/v0.0.1/node-shell_darwin_amd64.tar.gz
      sha256: "98b6e1a6383549c05d686e4b7e0bd720c668c19055c4ddeb29c3780fee7a1087"
      files:
        - from: "./node-shell"
          to: "."
        - from: LICENSE
          to: "."
      bin: "node-shell"
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/Moon1706/node-shell/releases/download/v0.0.1/node-shell_darwin_arm64.tar.gz
      sha256: "9cbc7a9a9787cd2e01df022d97502892620b1337bad6e430bd05b5486ffa7200"
      files:
        - from: "./node-shell"
          to: "."
        - from: LICENSE
          to: "."
      bin: "node-shell"
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/Moon1706/node-shell/releases/download/v0.0.1/node-shell_windows_amd64.zip
      sha256: "e26152c441aedfd5c1574e1ebb5875eab8a4c50b78412a1906514178beadc7c3"
      files:
        - from: "/node-shell.exe"
          to: "."
        - from: LICENSE
          to: "."
      bin: "node-shell.exe"
  shortDescription: A new plugin
  homepage: https://github.com/Moon1706/node-shell
  caveats: |
    Usage:
      $ kubectl node-shell --debug-image=<debug-image> --nodename=<node-to-run-on>

    For additional options:
      $ kubectl node-shell --help
      or https://github.com/Tinkoff/node-shell/blob/main/README.md

  description: |
    Kubectl plugin to run on a specific node with host filesystem mounted and escalated privileges
